name: "React-CD Pipeline/workflow"

on:
    workflow_run:
        workflows: ["React-CI-Pileline/workflow"]
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:

            - name: ubuntu update
              run: sudo apt-get update

            - name: Node.js setup
              uses: actions/setup-node@v4
              with:
                node-version: 22.18.0
            
            - name: Setup vercel CLI
              run: npm install -g vercel@latest

            - name: Check vercel version
              run: vercel --version

            - name: Download build files
              uses: actions/download-artifact@v4
              with:
                name: build           # <--- This must match the CI workflow
                run-id: ${{ github.event.workflow_run.id}}
                github-token: ${{ github.token }}

            - name: Deploy to Vercel
              run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes --name=cicd-pipeline .next